export const CONSTANTS = {
  //   API
  GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FAIL: 'GET_ALL_PRODUCTS_FAIL',

  //   CART
  ADD_CART_REQUEST: 'ADD_CART_REQUEST',
  ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
  ADD_CART__FAIL: 'ADD_CART_FAIL',
  REMOVE_CART_REQUEST: 'REMOVE_CART_REQUEST',
  REMOVE_CART_SUCCESS: 'REMOVE_CART_SUCCESS',
  REMOVE_CART_FAIL: 'REMOVE_CART_FAIL',
  GET_PRODUCT_COUNT: 'GET_PRODUCT_COUNT',
};
